# Generated by Django 4.2.1 on 2023-05-30 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_quit_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='quit_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
