# Generated by Django 4.2.1 on 2023-05-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_customuser_quit_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='quit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rejection_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
